services:
  - type: web
    name: midi-generation-service
    env: docker
    region: oregon
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: TEMP_DIR
        value: /tmp
    healthCheckPath: /health
